#Fazer um programa (na linguagem de sua preferência) para gerar números
#pseudo-aleatórios utilizando o método congruente linear. Escolha parâmetros a e M suficientemente
#grandes para que os números gerados sejam, de fato, pseudo-aleatórios. Gerar 100
#números entre [0, 1] (dividir por M e pegar apenas a primeira casa decimal, para que os valores
#sorteados sejam discretizados em intervalos de 0.1 em 0.1, isto é, [0:0.1; 0.1:0.2; 0.2:0.3; ...
#0.9:1]). Gerar gráfco da frequencia relativa dos intervalos.
#Usando o gerador nativo da linguagem escolhida por você, repita o processo para gerar
#1000 números. HGere o gráfico e compare os resultados.


# -*- coding: utf-8 -*-
"""Atividade5_AndreAraujo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-gaXqD-ipr2n_9w_27W6zjux1_ZbtEsQ
"""

# Função de geração de numero aleatorios
def linearCongruentialMethod(Xo, m, a, c, randomNums, noOfRandomNums): 

# inicialização da semente 
    randomNums[0] = Xo 

   
    for i in range(1, noOfRandomNums): 

        
        randomNums[i] = ((randomNums[i - 1] * a) + c) % m 


if __name__ == '__main__': 
    
 # semente
    Xo = 17 
      
    # parametro do modulo
    m = 256 
      
    # termo multiplicador
    a = 1

    # termo multiplicador
    c = 121
    
    noOfRandomNums = 100

    # To store random numbers 
    randomNums = [0] * (noOfRandomNums) 

    # Function Call 
    linearCongruentialMethod(Xo, m, a, c, randomNums, noOfRandomNums) 
    
    # Print the generated random numbers 
    for i in randomNums:
        
        print(i/m, end = " ") 


import matplotlib.pyplot as plt

Lista = [float(i) / m  for i in randomNums]

plt.hist(Lista, 100, rwidth=1)
plt.title('Gráfico Para 100')
plt.ylabel('Frequência ')
plt.show()



# Função de geração de numero aleatorios
def linearCongruentialMethod(Xo, m, a, c, randomNums, noOfRandomNums): 

# inicialização da semente 
    randomNums[0] = Xo 

   
    for i in range(1, noOfRandomNums): 

        
        randomNums[i] = ((randomNums[i - 1] * a) + c) % m 


if __name__ == '__main__': 
    
 # semente
    Xo = 17 
      
    # parametro do modulo
    m = 256 
      
    # termo multiplicador
    a = 1

    # termo multiplicador
    c = 121
    
    noOfRandomNums = 1000

    # To store random numbers 
    randomNums = [0] * (noOfRandomNums) 

    # Function Call 
    linearCongruentialMethod(Xo, m, a, c, randomNums, noOfRandomNums) 
    
    # Print the generated random numbers 
    for i in randomNums:
        
        print(i/m, end = " ") 

import matplotlib.pyplot as plt

Lista = [float(i) / m for i in randomNums]

plt.hist(Lista, 1000, rwidth=1)
plt.title('Gráfico Para 1000')
plt.ylabel('Frequência ')
plt.show()
